### ISSUE TITLE
where to get COZE_JWT_OAUTH_CLIENT_ID in JWT OAuth App?

### ISSUE THREAD

**Issue by zhjunqin** [coze-dev/coze-py#108]
where to get COZE_JWT_OAUTH_CLIENT_ID for server kind oauth app?

There are only COZE_JWT_OAUTH_PRIVATE_KEY and COZE_JWT_OAUTH_PUBLIC_KEY_ID.

```
import os
from cozepy import Coze, TokenAuth, JWTOAuthApp

# client ID
jwt_oauth_client_id = os.getenv("COZE_JWT_OAUTH_CLIENT_ID")
# private key
jwt_oauth_private_key = os.getenv("COZE_JWT_OAUTH_PRIVATE_KEY")
# public key id
jwt_oauth_public_key_id = os.getenv("COZE_JWT_OAUTH_PUBLIC_KEY_ID")

jwt_oauth_app = JWTOAuthApp(
    client_id=jwt_oauth_client_id,
    private_key=jwt_oauth_private_key,
    public_key_id=jwt_oauth_public_key_id,
)
```
![image](https://github.com/user-attachments/assets/36fe7f6e-91bc-4fb6-b116-1f7477688bfb)
![image](https://github.com/user-attachments/assets/e1169ac3-ea49-4b83-839d-7989d482f2cd)

**Comment by zhjunqin** [comment]
> where to get COZE_JWT_OAUTH_CLIENT_ID for server kind oauth app?
> 
> There are only COZE_JWT_OAUTH_PRIVATE_KEY and COZE_JWT_OAUTH_PUBLIC_KEY_ID.
> 
> ```
> import os
> from cozepy import Coze, TokenAuth, JWTOAuthApp
> 
> # client ID
> jwt_oauth_client_id = os.getenv("COZE_JWT_OAUTH_CLIENT_ID")
> # private key
> jwt_oauth_private_key = os.getenv("COZE_JWT_OAUTH_PRIVATE_KEY")
> # public key id
> jwt_oauth_public_key_id = os.getenv("COZE_JWT_OAUTH_PUBLIC_KEY_ID")
> 
> jwt_oauth_app = JWTOAuthApp(
>     client_id=jwt_oauth_client_id,
>     private_key=jwt_oauth_private_key,
>     public_key_id=jwt_oauth_public_key_id,
> )
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7519482/382572878-36fe7f6e-91bc-4fb6-b116-1f7477688bfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzkzMzIsIm5iZiI6MTczMDYzOTAzMiwicGF0aCI6Ii83NTE5NDgyLzM4MjU3Mjg3OC0zNmZlN2Y2ZS05MWJjLTRmYjYtYjExNi0xZjc0Nzc2ODhiZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMTMwMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNiOWMxZjM5YjkxYjA0NjE1YTY5YTBkZmIxZTk0ZDhjMzA3Y2QzMWFkZjVlMjAyOGM5ZGIzZTMxM2UwOWE2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oztfRATo6gbQds6BgdKxWdjX9ybGAxy6NSXEYgby_xw) ![image](https://private-user-images.githubusercontent.com/7519482/382572907-e1169ac3-ea49-4b83-839d-7989d482f2cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzkzMzIsIm5iZiI6MTczMDYzOTAzMiwicGF0aCI6Ii83NTE5NDgyLzM4MjU3MjkwNy1lMTE2OWFjMy1lYTQ5LTRiODMtODM5ZC03OTg5ZDQ4MmYyY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMTMwMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMzMWExYWE0YTcxOTEwY2Q2NTQ2ZGE3MjFjZGUwNWRkM2Y2OTc0NDVlYTAxN2VlZTg0Y2MzYWI0MTMwOTAyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.c8JgSYPvmhtc208DSErpTnaGQXuFmQwUQkxVxntIN7g)


if set to None

jwt_oauth_client_id = None

server return 404
coze_api_base = "https://api.coze.cn/"
cozepy.exception.CozeAPIError: code: 404, msg: , logid: 2024110320522477421C770F040778ABB4

**Comment by chyroc** [comment]
```diff
- coze_api_base = "https://api.coze.cn/"
+ coze_api_base = "https://api.coze.cn"
```
fix this

**Comment by chyroc** [comment]
https://github.com/coze-dev/coze-py/pull/109
