### ISSUE TITLE
OAuth JWT 授权：invalid jwt: kid not been registred

### ISSUE THREAD

**Issue by Mrchenvvv** [coze-dev/coze-py#123]
按照示例代码，在进行OAuth JWT 授权授权时提示“invalid jwt: kid not been registred”，公钥ID和私钥均来自OAuth 应用，公钥需要怎么注册呢？client_id传的None，详细代码如下：
coze_api_base = COZE_COM_BASE_URL
# client ID
jwt_oauth_client_id = None
# path to the private key file (usually with .pem extension)
jwt_oauth_private_key_file_path = COZE_PRIVATE_KEY_PATH
# public key id
jwt_oauth_public_key_id = self.cfg.PUBLIC_KEY_ID

if jwt_oauth_private_key_file_path:
    with open(jwt_oauth_private_key_file_path, "r") as f:
        jwt_oauth_private_key = f.read()
        
jwt_oauth_app = JWTOAuthApp(
    client_id=jwt_oauth_client_id,
    private_key=jwt_oauth_private_key,
    public_key_id=jwt_oauth_public_key_id,
    base_url=coze_api_base,
)
# Generate the authorization token
# The default ttl is 900s, and developers can customize the expiration time, which can be
# set up to 24 hours at most.
oauth_token = jwt_oauth_app.get_access_token(ttl=3600)

**Comment by chyroc** [comment]
kid 是公钥指纹，不是公钥

**Comment by Mrchenvvv** [comment]
> kid 是公钥指纹，不是公钥

![image](https://github.com/user-attachments/assets/d69e074c-4e88-44d4-aeb0-074bc78898b4)
请问一下是这个值吗？

**Comment by chyroc** [comment]
是的

**Comment by Mrchenvvv** [comment]
也不知道为什么 重新生成了公私钥 并且jwt_oauth_client_id传应用ID 就可以了
