### ISSUE TITLE
通过pythonSDK的方式JWT 鉴权方式报错

### ISSUE THREAD

**Issue by Gavingx** [coze-dev/coze-py#148]
运行https://github.com/coze-dev/coze-py/blob/main/examples/auth_oauth_jwt.py 里面的python代码，并且已经按照正确的方式构建了OAuth应用并授权且正确提供了公钥指纹，为什么还是抛出异常：
cozepy.exception.CozeAPIError: msg: invalid jwt: kid not been registred, logid: 2024122509064484DEDF525AF13E290496

**Comment by chyroc** [comment]
域名是否正确设置了？

**Comment by Gavingx** [comment]
> 域名是否正确设置了？

啊，还真是，我没有设置环境变量，默认取的非CN的，改完后可以了，谢谢
