### ISSUE TITLE
Retrieve the tokens spent on the request.

### ISSUE THREAD

**Issue by MSITETOP** [coze-dev/coze-py#81]
I couldn't retrieve the tokens spent on the request. How can I obtain this information in the SDK?

**Comment by chyroc** [comment]
there are four oauth auth examples in examples folder，are you finding it？

**Comment by MSITETOP** [comment]
Yes, of course. But I don't understand how this relates to my question? I need to obtain the number of spent coze tokens in the conversation using the method coze.chat.create_and_poll(), for example. Previously, I received this in the "conversation.chat.completed" event with data['usage']['token_count']. I couldn't find similar data in the SDK.

**Comment by chyroc** [comment]
fixed by https://github.com/coze-dev/coze-py/pull/82

**Comment by MSITETOP** [comment]
it's amaising
