### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by CapDuan** [coze-dev/coze-py#83]
<img width="455" alt="image" src="https://github.com/user-attachments/assets/1fb80329-f16e-42a4-9904-129111760295">
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/c97f5ee9-fbd3-44d9-81bc-fb2f45208167">

botId 和 pat秘钥都检查过 依然报错如下

“logid=2024101607163785A012E913E61573799A, code=4100, msg=authentication is invalid”

**Comment by chyroc** [comment]
https://github.com/coze-dev/coze-py/blob/main/examples/auth_pat.py#L19

**Comment by chyroc** [comment]
通过 base_url 设置为 cn
