### ISSUE TITLE
本地可以运行但为什么上传到服务器环境 运行他提示引入包错误这是为什么呢

### ISSUE THREAD

**Issue by 838111807** [coze-dev/coze-py#89]
cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)
本地虚拟环境可以运行，但为什么把依赖和应用文件一起打包到package上传到服务器环境 运行他提示引入包错误这是为什么呢
![image](https://github.com/user-attachments/assets/9ac00169-4d63-45dd-9cab-f02041eb0931)
![image](https://github.com/user-attachments/assets/ede0ce68-df2e-4a51-832f-61ffa8146a02)

**Comment by chyroc** [comment]
不要打包依赖，而是在服务器中安装依赖。

**Comment by 838111807** [comment]
> 不要打包依赖，而是在服务器中安装依赖。

不好意思上面描述错了，如果是本地包来运行，他这里有个警告，虚拟环境是正常
![image](https://github.com/user-attachments/assets/cbd8f215-91ed-4842-8078-1db52656b6ee)
本地包环境来使用时，这里有个警告
![image](https://github.com/user-attachments/assets/aa04b9df-49d7-4bae-afd1-7b5fdbfe64c8)

**Comment by 838111807** [comment]
本地我重新安装了Python 3.10.11，ok正常不报错
我测试了一下，换个python版本解决了
AWS Lambda，当平台使用的python环境是"3.8.19 (default, Sep  9 2024, 15:07:23) \n[GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]"
才会报错的
{
      "errorMessage":"Unable to import module 'index': cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)",
      "errorType":"Runtime.ImportModuleError",
      "stackTrace":[

      ]
    }

**Comment by chyroc** [comment]
本 sdk 只支持 3.7 以上
