### ISSUE TITLE
How to use custom_variables in Coze?

### ISSUE THREAD

**Issue by MSITETOP** [coze-dev/coze-py#98]
Hi,

I am currently passing the parameter custom_variables as a dictionary with the value {"chat_id": "123456"} in my API request. In Coze, I added chat_id under Variables and configured it as a required value within my plugin.
![Снимок экрана 2024-10-28 154338](https://github.com/user-attachments/assets/de835114-caa8-4d4d-bab8-2a7a092e1e23)

However, it seems that Coze is not passing the parameter provided in the API call when invoking the plugin.
![Снимок экрана 2024-10-28 154416](https://github.com/user-attachments/assets/1ca5e5aa-6eda-4c3a-aa8f-a6d84f1244d6)
![Снимок экрана 2024-10-28 154402](https://github.com/user-attachments/assets/8c561c39-2e01-4fa4-9cd9-3e3a377fd1c1)

And 
How can I set up local plugins in the Coze interface to ensure they are called correctly?
https://github.com/coze-dev/coze-py/blob/main/examples/chat_local_plugin.py

 Could you please assist me with this issue?.

**Comment by chyroc** [comment]
custom_variables is only supported with prompt, not support with plugin input params.

detail description:

https://www.coze.com/docs/developer_guides/chat_v3#3b7ad181

The customized variable in a key-value pair. After setting variables in the agent prompt with {{key}}, you can pass in the variable values through this parameter, and Jinja2 syntax is also supported. For more information, see 'Prompt Variables'.

**Comment by MSITETOP** [comment]
Thanks! I will try to use this.
